### ISSUE TITLE
This is more of a question asking this here because modrinth has no comment section and you don't have a discord

### ISSUE THREAD

**Issue by Noahfrechette** [edayot/SimpleDrawer#13]
How do I add the datapack at server start?

**Comment by edayot** [comment]
You install it like a normal datapack, but you need to restart the server to use it.

It will not work if don't restart the server.

**Comment by Noahfrechette** [comment]
what if the server is off and I add it?

**Comment by edayot** [comment]
Yes it will work, if it doesn't just restart the server and u will be good to use th datapack

**Comment by Noahfrechette** [comment]
Thanks!

**Comment by Noahfrechette** [comment]
I will close this
