### ISSUE TITLE
No upgrades when filled

### ISSUE THREAD

**Issue by CptGummiball** [edayot/SimpleDrawer#19]
It would be nice if you could upgrade the drawers while they are full

**Comment by edayot** [comment]
Hi, I tested on a normal drawer and it seems to work fine, what type of drawer are you using and what version of simpledrawer is installed ?

**Comment by CptGummiball** [comment]
We tested it again and it now seems to be working. Whatever the reason, it didn't work. We using v1.11.2

**Comment by edayot** [comment]
I will investigate a bit more into this, thank for the report.
