### ISSUE TITLE
Hopper upgrade not working

### ISSUE THREAD

**Issue by CptGummiball** [edayot/SimpleDrawer#20]
We applied a hopper upgrade to the drawer, but it doesn't accept any input. Tried it from all sides.

**Comment by edayot** [comment]
Hi, I tested and it's working fine, where did you downloaded the datapack ?


https://github.com/edayot/SimpleDrawer/assets/35682876/120d1ab6-ac56-44b3-afb5-64b8f289d61f

**Comment by CptGummiball** [comment]
we use [v1.11.2] from modrinth.
Currently run on PaperMC 1.20.2 Build 318

**Comment by edayot** [comment]
Sorry for this late response, but I will test if it's an easy fix on paper, but usually paper breaks some datapacks.

**Comment by CptGummiball** [comment]
We will also do a few tests. If you find a solution that would be great. If we find a solution we will share it here.

**Comment by edayot** [comment]
Can you give me the world download, I tested on paper myself and it's working fine. But I think I know the issue.

**Comment by CptGummiball** [comment]
That could be a problem. our world is 32 GB in size.  What could be the error? Then I could test it directly since I'm working on the server anyway.

**Comment by edayot** [comment]
Oh ok can you try theses things :
1. Use the hopper upgrade at `/tp @s -30000000 20 1610` in the overworld ?
2. Do `/tag @s add convention.debug` and `/reload` and show me the chat ? ( `/tag @s remove convention.debug` to get ride off this)

**Comment by CptGummiball** [comment]
ok this crashed the server.

**Comment by edayot** [comment]
just the fact of loading the area ?

**Comment by CptGummiball** [comment]
With /reload the server crashed almost immediately and I had to load a backup because some plugins could no longer load afterwards

**Comment by edayot** [comment]
sorry for that, i was not expecting theses simples steps to crash your server
btw what's the list of plugins/datapacks that you have ?

**Comment by CptGummiball** [comment]
Plugin list:
Paper Plugins:
BKCommonLib, ExtraDatabasesH2, Minepacks, TicketManager
Bukkit Plugins:
AntiPopup, AxGraves, AxShulkers, AxSmithing, BeautyQuests, BlockEffects, BlockProt, BoomBox, Celebrate, ChristmasPlus,
Chunky, ChunkyBorder, Citizens, CitizensGUI, ClickHarvest, ColoredAnvils, CommandButtons, CoreProtect, CustomCommands, DataPackLoader
Denizen, Disenchantment, DropEdit2, EmployMe, EntityClearer, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsSpawn, FancyHolograms,
FarmControl, GCore, GSit, HarderDespawn, HsRails, Item-Chest-Sorter, ItemSoulBind, Lands, LibsDisguises, LuckPerms
Maintenance, MiniMOTD, MTDeathLocator, Multiverse-Core, Multiverse-Portals, NoteBlockAPI, Pl3xMap, Pl3xMap-Banners, Pl3xMap-Claims, PlaceholderAPI, PlayerStats, PostOffice, ProtocolLib, Skulls, spark, StreamingDrops, TAB, TCDestinations, TeaksTweaks, Tether, TheDragon, TimeIsMoney, Train_Carts, TreeFeller, UberEnchant, UltimateAutoRestart, UltimateCaves, Vault, ViaBackwards, ViaVersion, VillagerFollow, VillagerMarket, voicechat, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldGuard, TabCompletion, YamipaPlugin

Datapacks:
better hanging signs v3.45
ItemFrameColor2.1
jingle-s-christmas-datapack-1-20-2
joshs-more-foods-datapack-v4.1.4
more_mobs-v1.5-mc1.14x-1.20x-datapack
Rocket Riding v1
SimpleDrawer-v1.11.2-Datapack-Bundled
SmeltingStoneInBlastFurnace
table-games(v3.2)
Tool-Rack-Data-Pack-1.20
Woodcutter

**Comment by CptGummiball** [comment]
Everything that could block Hopper has been switched off. At least in the regions where we tested it

**Comment by edayot** [comment]
That a lot of plugins, but i think that there is a problem at the worldborder, maybe an other datapack but i don't really know.

The problem can appear because a entity is missing at theses coordonate, it affect itemstacking (like stacking swords) and hoppers upgrades i think.

**Comment by CptGummiball** [comment]
But why should there be an entity there? I haven't looked at the data pack code in more detail. But does an entity have to be created for it to work? On our server, an entity CANNOT spawn outside of the player radius.

If it has something to do with stacking it becomes difficult because paper automatically stack items to one pile to avoid lagging

**Comment by CptGummiball** [comment]
I will do some Tests on our TestServer for Updates and add updates one after another and look if one of them breaks the hopper upgrade

**Comment by edayot** [comment]
It's only a single armor stand, it's used to prevent item stack, generate Lores for the drawer, it's very convenient for a lot of usages in datapacks.

**Comment by CptGummiball** [comment]
I think i found the problem^^ ChunkyBorder blocks Entity Spawning outside the Border. I changed this in the cofigs and now its working fine.

**Comment by CptGummiball** [comment]
![Capture](https://github.com/edayot/SimpleDrawer/assets/151415484/a61d9e7e-aab1-4998-ae07-33360577ce74)

prevent mob spawns has to be set to false. and then it works fine

**Comment by edayot** [comment]
Good you find a workaround, I close the issue.
