### ISSUE TITLE
Currently no recipes working on 1.20.4 (as aspected)

### ISSUE THREAD

**Issue by CptGummiball** [edayot/SimpleDrawer#21]
## Describe the bug
*Recipes in Heavy Workbench not working*

## How to reproduce
*Use this Datapack with 1.20.4 Client or Server*

## Context
Simpledrawer : *1.11.2 from Modrinth*
Minecraft versions: *1.20.4*
Others mods / datapacks installed : *Many but no difference when not using them*

Additional:
*Not a bug per se, just an indication that the datapack breaks with 1.20.4. I hope there will be an update for this. I also know that Smithed has to bring an update here first. All datapacks with smithed are currently glitching into each other with 1.20.4*
*There are a translation Bug because of Mojangs new "grass" name "short_grass" for us i fixed that but it has to be changed in future updates of this datapack"

1.20.4 can't parse some jsons:
https://paste.gg/p/anonymous/fe1aeb9837d341ef9cc4fa8ec06354e7 (the translation jsons not working because of the "grass" as mentioned before)

**Comment by edayot** [comment]
Hi, yes I will certainly wait for an smithed (I don't have time to make a PRs), also as you noticed the translations don't work, but it will be fixed very easily I think.

**Comment by CptGummiball** [comment]
yes as far i have seen there only two files with the grass thing ^^

**Comment by edayot** [comment]
Here's the smithed [PR](https://github.com/Smithed-MC/Libraries/pull/38), waiting until it's merged & released to be compatible with MC 1.20.4

**Comment by CptGummiball** [comment]
Sounds great. In the meantime, I have created a shop on our server where you can buy the drawer so that it can continue to be used until the recipes work again.

**Comment by CptGummiball** [comment]
When we update the Datapack, is there something to do first? Disable the old one bevore restart or simply replace it? As i read Simple Drawer has to be load by server start.

**Comment by edayot** [comment]
Replace it should be fine in most case if the server was already loaded with the datapack but if you experience visual bugs on the drawers, simply restart the server.

Not restarting makes only visual bugs in the worst case.

**Comment by CptGummiball** [comment]
Hi, any news about this? As i've seen your PR was merged

**Comment by edayot** [comment]
I asked to trigger the workflow on discord to publish the versions for 1.20.4, but it's delayed

**Comment by edayot** [comment]
Closing this issue, the datapack is working in 1.21
