### ISSUE TITLE
We want to add Simple Drawer Support to our Plugin

### ISSUE THREAD

**Issue by CptGummiball** [edayot/SimpleDrawer#22]
**Hi, we think that the Simple Drawer Datapack is really worth it and therefore want to add the support for it into our plugin.**

https://www.spigotmc.org/resources/mcdealer-plugin-version.113974/
_(There is also our standalone version but we are currently concentrating on the plugin)_ 

Our plugin is the web view for Villagermarket. It allows players to get an overview of the server's shop offerings. Currently it ONLY supports Villagermarket, but we chose VM for a reason.
Without wanting to advertise much, it is pretty much the best Villager Shop plugin currently available.

https://www.spigotmc.org/resources/villager-market-the-ultimate-shop-plugin.82965/

Well, as I said, we would like to add support for Simple Drawer into our plugin and wanted to ask you for permission to do so, because we need the item graphics for this. If you agree, a list of all IDs would be very helpful.

_A link to your datapack will of course also be added in the plugin description_

**Comment by edayot** [comment]
Sure, you can add support for SimpleDrawer for your plugin, that's what's the MIT license is for.

But what do you mean by a list of all IDs ?

**Comment by CptGummiball** [comment]
Usually , items from data packs have their own names (ID). The book, for example, is called “simpledrawer.guide”

You can see this in the screenshot below. In our Web overview theres the own_name (Our Plugin can translate these to a clear Item Name)

![image](https://github.com/edayot/SimpleDrawer/assets/151415484/17544660-2e84-4f30-a002-c9d5524902b8)

**Comment by edayot** [comment]
It's a little bit more complex than that for simpledrawer, especially for the drawers.

Here's some commands for normal items : 
l```mcfunction
oot give @s loot simpledrawer:impl/items/guide
loot give @s loot simpledrawer:impl/items/hopper_upgrade
loot give @s loot simpledrawer:impl/items/iron_upgrade
loot give @s loot simpledrawer:impl/items/gold_upgrade
loot give @s loot simpledrawer:impl/items/diamond_upgrade
loot give @s loot simpledrawer:impl/items/star_upgrade
loot give @s loot simpledrawer:impl/items/netherite_upgrade
loot give @s loot simpledrawer:impl/items/downgrade_wrench
```
They all have a unique smithed.id NBT Tag associated with a unique CustomModelData.

For the drawers it's a little bit more complex, the command `/function simpledrawer:v1.11.2/give_all` will give you all combinaisons each of them as a unique CustomModelData AND TrimMaterial (this is for supporting all wood types) BUT the same smithed.id

**Comment by CptGummiball** [comment]
Okay, then we'll do it the same way as with smaller data packs and see what kind of data our output file stores. Then we can build the filter. 
Normally it looks something like this: “datapacksname:itemgroup:item”.
Our plugin is currently based on this and assigns the translation and the image.
It'll take a bit of work if it's more complex in this case, but we'll get it done. We will contact you as soon as it is ready

**Comment by CptGummiball** [comment]
Ah okay, thx :)

**Comment by CptGummiball** [comment]
Ok, so we can't currently implement SimpleDrawer because unfortunately the VM doesn't save the armor trims so that we can read them out using our script. Therefore the wood type cannot be displayed correctly. Luckily the contents of the drawer are stated in the lore, so at least that should be displayed correctly with our next update. Unfortunately, icons are still displayed incorrectly and item names are still displayed something like "simpledrawer.drawer". I have now moved the whole thing to v1.3.0 which means that this feature will only be added in a later version once we have figured out how and where VM stores the necessary data.

**Comment by CptGummiball** [comment]
We found a way to get the data. So we will add the feature with 1.2.0. It just takes a while because we have to change a few things in the script.
But thank you in advance, as the new function now gives us more options for integrating other data packs and plugins

**Comment by CptGummiball** [comment]
Hi,
our project is no longer being developed or supported. Instead, we started developing the successor, which will be more lightweight. The Simple Drawers data will then no longer be directly integrated. Datapack and Plugin Support will only be available in a later version and will require manual management by the user. [MCDealer2](https://github.com/CptGummiball/MCDealer2)
