### ISSUE TITLE
Infinitely obtainable base blocks

### ISSUE THREAD

**Issue by FracturedFlux** [edayot/SimpleDrawer#34]
## Describe the bug
All base blocks delete a tick late, causing TCC to pick them up with the Tangling Pearl

## How to reproduce
> Install SimpleDrawers and TCC (I used a smithed bundle, so welded.)
> Give yourself a Tangling Pearl from TCC and activate it
> Place any SimpleDrawers block
> Break it in Survival
You get both the SimpleDrawers block, and the block it uses as a base (beehive, lodestone, etc.)

## Context
Simpledrawer : v2.1.1 from Smithed
Minecraft versions: 1.21
Others mods / datapacks installed : Valiance, TCC

**Comment by edayot** [comment]
I see why it does that, simpledrawer is only checking for one block around the destroy point for items to kill, if the items moved out of this region before (like with the Tangling pearl) they are not killed.

**Comment by FracturedFlux** [comment]
ideally for stuff like this, simpledrawer would use blocks with data like droppers, barrels etc but i'm sure there's a reason for it not doing so

**Comment by edayot** [comment]
I'm not sure it's my fault, this is also happening because : the tangling pearl is teleporting the item before i check for it in simpledrawer.

I will check if there is something to filter it in the creeper code, but if i can't do anything, it's tcc fault, not mind (or a convention fault).

**Comment by edayot** [comment]
The related issue is resolved, so this task is done.
