### ISSUE TITLE
FPS lag...

### ISSUE THREAD

**Issue by JamesDAdams** [edayot/SimpleDrawer#35]
Verry good idea for a datapack but unusable, with 20/30 storage i'm switch from 500fps to 80fps :/

**Comment by edayot** [comment]
Hi, first i'm taking the problem very seriously, but : 
- There is a issue template that provide a good context for me to understand the problem, i would like you to fill it
- I tested on my PC, i drop from 1000fps to 100fps with 600 drawers

![Image collée (2)](https://github.com/user-attachments/assets/87314f69-a647-4e54-a715-733b8eb48e89)

**Comment by edayot** [comment]
I'm also considering to add a config UI to Simpledrawer for a long time, with a performance, and a functionality menu

**Comment by edayot** [comment]
Also we can speak in french if you want

**Comment by JamesDAdams** [comment]
> Hi, first i'm taking the problem very seriously, but :
> 
> * There is a issue template that provide a good context for me to understand the problem, i would like you to fill it
> * I tested on my PC, i drop from 1000fps to 100fps with 600 drawers
> 
> ![Image collée (2)](https://private-user-images.githubusercontent.com/35682876/387791606-87314f69-a647-4e54-a715-733b8eb48e89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwOTIwNTIsIm5iZiI6MTczMjA5MTc1MiwicGF0aCI6Ii8zNTY4Mjg3Ni8zODc3OTE2MDYtODczMTRmNjktYTY0Ny00ZTU0LWE3MTUtNzMzYjhlYjQ4ZTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDA4MzU1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1NDc1YzU5MzdiZTk4MGJhOGE5ZjA4Y2FjNmE0ZmZiYTE3Mjg2ZDU1MDFmM2UxMTFmNTViZWNhMDMwM2M3OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bU1nLZlFNB4aCtxaBHOIF3yEgYfcjE4GVZj7d7yWobU)

Hi,

thanks for the fast reply, can you send me your map for my test ?
We can continue in english if other people read this issues :)

**Comment by edayot** [comment]
Please fill the issue template

**Comment by edayot** [comment]
With the latest release, you can tune the LOD params using `/function simpledrawer:config`. It will certainly imrove performance, I close the issue, but don't hesitate to reopen it.
