### ISSUE TITLE
Getting inventory spammed with Crafters from Smithed Crafting

### ISSUE THREAD

**Issue by Nerdtality** [edayot/SimpleDrawer#8]
Getting inventory spammed with Crafters from Smithed Crafting,
I used the bundled ZIP file and get spammed with Crafters about every 20 ticks.

**Comment by edayot** [comment]
Hi,
I don't see any problem, i launched a new world with only the bundled files and nothing seems to spam.

Can you be more precise on the problem and some test conditions you are using ? It can be another datapack that makes things totally broken.

**Comment by Nerdtality** [comment]
Let me do some more testing, I am running a mix of Fabric Mods and Datapacks.

**Comment by edayot** [comment]
If you not telling me the test conditions I can't help you, but mods and datapack don't usually work together.
